export { AboutSection } from './About/About';
export { InfoSection } from './Info/Info';
export { EngineSection } from './Engine/Engine';
export { RewardsSection } from './Rewards/Rewards';
export { TrailerSection } from './Trailer/Trailer';
export { RoadmapSection } from './Roadmap/Roadmap';
export { TeamSection } from './Team/Team';
export { TokenomicsSection } from './Tokenomics/Tokenomics';
export { FooterSection } from './Footer/Footer';
